Implementation of Track Data Availability
IMAP-Science-Operations-Center/sds-data-manager pull request #120
Opened 2023-08-01 21:57 UTC by tech3371

# Change Summary
This is initial implementation of issue [Data Tracket Implementation](https://github.com/IMAP-Science-Operations-Center/sds-data-manager/issues/96)

## Overview

We need a database to track processing. In this review, there are two ways to track processing.
1. Use DynamDB to track processing
2. Use existing opensearch database

## New Dependencies

## New Files
- sds_data_manager/lambda_code/SDSCode/dynamodb_utils/processing_status.py
   - Defines processing status enum
- sds_data_manager/stacks/dynamodb_stack.py
   - Creates DynamoDB resources using this stack
  
## Deleted Files

## Updated Files
- sds_data_manager/lambda_code/SDSCode/indexer.py
   - Added code in indexer lambda to take injested data information and initialized data-tracker with default processing status.
   - Created new opensearch index to send same default processing status.
- updated file 2
   - descipriton of change 1 in file 2
- sds_data_manager/stacks/sds_data_manager_stack.py
   - Updated it take DynamoDB stack as input and use it to get and set environment variable of table name for indexer lambda
- sds_data_manager/utils/stackbuilder.py
   - Updated stack builder to create DynamoDB stack and updated input parameter of sds_data_manager_stack.
## Testing
- tests/infrastructure/test_dynamo_db_stack.py
   - This tests if DynamoDB stack creates resources as expected and checks some required settings.

2023-08-01 22:01 UTC, laspsandoval commented
Everything deploys and works. I had one additional comment that might be implemented in another PR. I also have a general question which is : Do you know why we chose to use OpenSearch for the APIs and then a separate DynamoDB for tracking processing? Somehow I missed that information along the way….

Besides that it all looks good. Nice work!

2023-08-01 22:01 UTC, laspsandoval approved these changes

2023-08-01 22:01 UTC, laspsandoval commented on sds_data_manager/lambda_code/SDSCode/indexer.py
> +def write_data_to_dynamodb(item: dict):
The code creates a new DynamoDB resource inside the write_data_to_dynamodb function every time it's called. If this function is called frequently, it could be more efficient to create the resource once and reuse it.

2023-08-01 22:08 UTC, tech3371 commented on sds_data_manager/lambda_code/SDSCode/indexer.py
> +def write_data_to_dynamodb(item: dict):
Yeah, for sure! like a global variable or create resource in the handler function and pass as argument?

2023-08-01 22:53 UTC, tech3371 commented
pre-commit.ci autofix

2023-08-02 01:56 UTC, tech3371 commented
I don't know why `test_indexer_lambda_iam_policy_resource_properties` test is failing. I tried fixing it but can't seem to fix it. It looks correct me but can't seems to pass it. Any suggestions?

2023-08-02 14:07 UTC, sdhoyt requested changes

2023-08-02 14:07 UTC, sdhoyt commented on tests/infrastructure/test_data_manager_stack.py
>                      {
```suggestion
                    {
                        "Action": [
                            "secretsmanager:GetSecretValue",
                            "secretsmanager:DescribeSecret"
                        ],
                        "Effect": "Allow",
                        "Resource": {"Fn::Join": ["", ["arn:", {"Ref": "AWS::Partition"}, Match.string_like_regexp(":secretsmanager:.*:secret:.*")]]},
                    }
```

2023-08-02 14:07 UTC, sdhoyt commented on tests/infrastructure/test_data_manager_stack.py
>                      {
I was able to get the test passing by replacing the secrets manager part with this. I got that format from writing the template json to a file and looking at it. I tried Matching the whole Resource entry, but that didn't work for some reason. I think it also didn't like that the GetSecretValue and DescribeSecret were out of order in that list. I'm not sure if I don't know what I'm doing or the cdk is just really annoying to test. But the code above should get the test passing and it seems to be what you were expecting. Let me know if you have any issues

2023-08-02 14:08 UTC, sdhoyt approved these changes

2023-08-02 14:25 UTC, tech3371 commented on tests/infrastructure/test_data_manager_stack.py
>                      {
Thank you for inspecting that. I wouldn't have done `Fn::Join` because I thought it's not needed since it was not getting arn or anything. 

Test did pass!!!

2023-08-02 14:26 UTC, tech3371 commented
pre-commit.ci autofix

2023-08-02 15:05 UTC, tech3371 commented
Thank you @laspsandoval and @sdhoyt for testing it! I am going to merge this PR now.

2023-08-02 15:07 UTC, merged