Batch starter
IMAP-Science-Operations-Center/sds-data-manager pull request #230
Opened 2024-01-24 17:16 UTC by laspsandoval

# Batch Starter Updates

## Overview

## New Dependencies

## New Files

- new file 1
   - description of new file 1's purpose

## Deleted Files

- deleted file 1
   - explanation for why file was deleted

## Updated Files

- updated file 1
   - description of change 1 in file 1
   - description of change 2 in file 2
- updated file 2
   - descipriton of change 1 in file 2

## Testing

2024-01-24 19:49 UTC, tech3371 approved these changes
I add few minor comments and about the instrument names in dependency json as we talked in person. Besides that, I think it looks great for the demo! It was much easier to follow and understand. nice work!

2024-01-24 19:49 UTC, tech3371 commented on sds_data_manager/lambda_code/batch_starter.py
> +    instrument = components["instrument"]
Don't worry about it for this PR. In upcoming PR, we can replace this with path_helper.py class. That's in review too.

2024-01-24 19:49 UTC, tech3371 commented on sds_data_manager/lambda_code/batch_starter.py
> +def find_dependencies(
logically, I follow it. Later, we can simplify this search by making query to pre-processing table. We can modify this later post demo.

2024-01-24 19:49 UTC, tech3371 commented on sds_data_manager/lambda_code/batch_starter.py
> +    Finds dependency information for each instrument.
Can you add a comment that this function is looking for upstream dependency of current downstream dependency?

2024-01-24 19:49 UTC, tech3371 commented on sds_data_manager/lambda_code/batch_starter.py
> +        if queried_instrument_dependencies == upstream_dependencies:
should this be a length comparison?

2024-01-24 19:49 UTC, tech3371 commented on sds_data_manager/lambda_code/batch_starter.py
> +def prepare_data(filename, upstream_dependencies, s3_bucket):
later, this function can be simplify or replaced by path_helper class.

2024-01-24 19:49 UTC, tech3371 commented on tests/lambda_endpoints/test_batch_starter.py
> +def _aws_credentials():
`conftest.py` in this directory already takes care of this. You can remove this and call it in functions that needs it.

2024-01-24 19:49 UTC, tech3371 commented on tests/lambda_endpoints/test_batch_starter.py
> +    base_path = base_directory.parents[2] / "sds_data_manager" / "lambda_code"
interesting. didn't know you go two folders up this way. nice!

2024-01-24 21:14 UTC, maxinelasp requested changes
A few comments, mostly related to making the docs very clear about upstream/downstream dependencies

2024-01-24 21:14 UTC, maxinelasp commented on tests/docker_images/imap_api.py
> +    parser.add_argument(
Is this all dependencies, or only downstream dependencies?

2024-01-24 21:14 UTC, maxinelasp commented on sds_data_manager/lambda_code/batch_starter.py
> +            models.FileCatalog.end_date <= datetime.strptime(end_date, "%Y%m%d"),
Does it make sense to move the database query methods into a different file that you can them import? Then it can be used in other pieces of code.

2024-01-24 21:14 UTC, maxinelasp commented on sds_data_manager/lambda_code/batch_starter.py
> +        A list of dictionaries containing dependency instrument,
Specify if this is upstream or downstream

2024-01-24 21:14 UTC, maxinelasp commented on sds_data_manager/lambda_code/batch_starter.py
> +        A list of dictionaries containing dependency instrument,
In general, I think it would be useful to get more info on what this actually looks like - what is the structure of the dict? How is it used? The dependencies are really confusing so being really clear will help, lol

2024-01-24 21:14 UTC, maxinelasp commented on sds_data_manager/lambda_code/batch_starter.py
> +                dependencies.append({"instrument": instr, "level": level})
So you are searching the dependencies provided in `data` to find if any of them have `downstream_dependent` as a dependency? Meaning this list is all the upstream dependencies of `downstream_dependent`?

2024-01-24 21:14 UTC, maxinelasp commented on sds_data_manager/lambda_code/batch_starter.py
> +                dependencies.append({"instrument": instr, "level": level})
Could you rename `dependencies` to a more descriptive name?

2024-01-24 21:14 UTC, maxinelasp commented on sds_data_manager/lambda_code/batch_starter.py
> +    Queries and checks if dependencies are available.
This method is called `query_upstream_dependencies` but takes in `downstream_dependents`. Could you add some more info in the method description about _what_ dependencies are looked for?

2024-01-24 21:14 UTC, maxinelasp commented on sds_data_manager/lambda_code/batch_starter.py
> +    for dependent in downstream_dependents:
Talked about this with Tenzin - but are these truly downstream_dependents, or are they the current records you are trying to find dependency information on? Could you rename this to "current_records" or something to make it clear that this is a list of records you are trying to find upstream dependencies for? (If I'm interpreting correctly...)

2024-01-24 21:14 UTC, maxinelasp commented on sds_data_manager/lambda_code/batch_starter.py
> +                queried_instrument_dependencies.append(
This is duplicating `upstream_dependencies` - perhaps instead, you could use a boolean value `all_dependencies_available` that switches to false once a dependency is not found. Then you can save the space and comparison between `upstream_dependencies` and `queried_instrument_dependencies`. I also think it would be more clear.

2024-01-24 21:14 UTC, maxinelasp commented on sds_data_manager/lambda_code/batch_starter.py
> +            record = query_instrument(
Would it make sense to make this query into a request for all the upstream dependencies? If you could make one request for all of them, it would eliminate this whole for-loop, which would be nice. If you're planning on changing the database setup (which I talked about with Tenzin) then leaving it like this is also fine

2024-01-24 21:14 UTC, maxinelasp commented on sds_data_manager/lambda_code/batch_starter.py
> +def prepare_data(filename, upstream_dependencies, s3_bucket):
Agreed with Tenzin that this should be pulled out for other code to use!

2024-01-24 21:14 UTC, maxinelasp commented on sds_data_manager/lambda_code/batch_starter.py
> +    with Session(engine) as session:
Nice, I like this section, the design works out to be very clear about when a batch job is started vs skipped!

2024-01-25 14:59 UTC, laspsandoval commented on tests/docker_images/imap_api.py
> +    parser.add_argument(
This is upstream dependencies only. And this is only a test script....not for the final processing. Only for the demo. The one that we will use more permanently is located at: imap_processing/examples.

2024-01-25 15:31 UTC, laspsandoval commented on sds_data_manager/lambda_code/batch_starter.py
> +                dependencies.append({"instrument": instr, "level": level})
Yes. That is correct. We are making a list of upstream dependencies of the downstream dependent.

2024-01-25 15:37 UTC, laspsandoval commented on sds_data_manager/lambda_code/batch_starter.py
> +    for dependent in downstream_dependents:
Downstream dependents are the candidates for the batch job. They will have records in the status table when the batch_starter.py completes. I'll put a note that they are candidates for the batch job.

2024-01-25 15:46 UTC, laspsandoval commented on sds_data_manager/lambda_code/batch_starter.py
> +            record = query_instrument(
Yes you are right. There is a better way to do this. I'll put it as a todo for when change the database setup.

2024-01-25 15:49 UTC, laspsandoval commented on sds_data_manager/lambda_code/batch_starter.py
> +            models.FileCatalog.end_date <= datetime.strptime(end_date, "%Y%m%d"),
That would be a nice to have. I have to think about what other pieces of code would use these.

2024-01-25 15:53 UTC, laspsandoval commented on sds_data_manager/lambda_code/batch_starter.py
> +                queried_instrument_dependencies.append(
I like your idea about dong a single query without a loop. I'll see if I can implement that.

2024-01-25 20:01 UTC, maxinelasp approved these changes
Nice, looks good!

2024-01-25 20:03 UTC, merged